```yaml
version: 0.0

os: linux

files:
  - source: todoapp.tar
    destination: /opt/todoapp

hooks:

  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 60
      runas: root
```
